export {default as FormButton} from '@/components/atoms/Button/FormButton'
export {default as DetailButton} from '@/components/atoms/Button/DetailButton'
export {default as Text} from '@/components/atoms/Text'
export {default as ErrorText} from '@/components/atoms/Text/ErrorText'
export {default as Svg} from '@/components/atoms/Svg'
export {default as Input} from '@/components/atoms/Input'
export {default as Textarea} from '@/components/atoms/Textarea'
